model:
  base_learning_rate: 4.5e-6
  target: taming.models.vqgan.VQModel
  params:
    embed_dim: 256
    n_embed: 1024
    # ckpt_path: logs/vqgan_SWFD_scBP_f16_1024.ckpt
    ddconfig:
      double_z: False
      z_channels: 256
      resolution: 256
      in_channels: 1
      out_ch: 1
      ch: 128
      ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0

    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 1
        disc_start: 10000
        disc_weight: 0.8
        codebook_weight: 1.0
        perceptual_weight: 0.0 #don't use imagenet loss

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 4
    num_workers: 14
    train:
      target: taming.data.unpaired_oadat.OADATDatasetSingleImage
      params:
        fname_h5: datasets/OADAT/SWFD_semicircle_RawBP.h5 
        groupname: sc_BP 
        inds_end: 37000
        inds_start: 0
        size: 256
    validation:
      target: taming.data.unpaired_oadat.OADATDatasetSingleImage
      params:
        fname_h5: datasets/OADAT/SWFD_semicircle_RawBP.h5 
        groupname: sc_BP 
        inds_end: 38000
        inds_start: 37000
        size: 256

